### ISSUE TITLE
v1.31.2 language server crashes in Zed

### ISSUE THREAD

**Issue by injust** [DetachHead/basedpyright#1429]
### Description

I have basedpyright installed as a uv tool. after upgrading from v1.31.1 to v1.31.2, the language server crashes on startup in Zed:

```
initializing server basedpyright, id 1
-- stderr--
node:internal/modules/cjs/loader:1368
  throw err;
  ^

Error: Cannot find module './dist/pyright-langserver'
Require stack:
- /Users/jsu/.local/share/uv/tools/basedpyright/lib/python3.13/site-packages/basedpyright/langserver.index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1365:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1021:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1026:22)
    at Function._load (node:internal/modules/cjs/loader:1175:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1445:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/jsu/.local/share/uv/tools/basedpyright/lib/python3.13/site-packages/basedpyright/langserver.index.js:8:1)
    at Module._compile (node:internal/modules/cjs/loader:1688:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jsu/.local/share/uv/tools/basedpyright/lib/python3.13/site-packages/basedpyright/langserver.index.js'
  ]
}

Node.js v22.18.0
```

**Comment by DetachHead** [comment]
i don't think any of the changes in this release could have caused this. perhaps something went wrong when updating and some of the files were not installed correctly, which can sometimes happen if you update basedpyright while the language server is running.

i suggest trying to uninstall and reinstall basedpyright. if that doesn't work, [delete your uv cache](https://docs.astral.sh/uv/concepts/cache/#clearing-the-cache) and try again

**Comment by injust** [comment]
Looks like it was a bad uv cache. `uv cache clean` plus a reinstall worked.

> which can sometimes happen if you update basedpyright while the language server is running

I see, this was probably the case.
